---
- name: Preparation before installing (Debian/Ubuntu)
  import_tasks: setting_deb.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Preparation before installing (CentOS/RHEL)
  import_tasks: setting_rpm.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install Kibana
  package:
    name: kibana
    state: present

- name: Create log directory
  ansible.builtin.file:
    path: "{{ '/'.join(logging_dest.split('/')[:-1]) }}"
    state: directory
    owner: root
    group: kibana
    mode: '0775'
  when: logging_dest != "stdout"

- name: Copy Kibana config file
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: '0664'

- name: Enable and start service
  service:
    name: kibana
    state: started
    enabled: yes

- name: Wait for Kibana startup
  wait_for: 
    host: "{{ server_host }}"
    port: "{{ server_port }}"
    delay: 5
    connect_timeout: 2
    timeout: 60