---
- name: Download and install the public signing key
  apt_key:
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic repository
  shell:
    cmd: echo "deb https://artifacts.elastic.co/packages/{{ version }}.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-{{ version }}.x.list
  register: echo

- name: Install dependencies
  apt:
    update_cache: yes
    pkg:
    - apt-transport-https